// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(public)/concluir_treino_page.dart' as a0;
import 'app/(public)/criar_conta_page.dart' as a1;
import 'app/(public)/criar_treino_page.dart' as a2;
import 'app/(public)/exercicios_page.dart' as a3;
import 'app/(public)/historico_page.dart' as a4;
import 'app/(public)/home_page.dart' as a5;
import 'app/(public)/login_page.dart' as a6;
import 'app/(public)/splash_page.dart' as a7;
import 'app/(public)/treino_page.dart' as a8;
import 'app/(public)/usuario_page.dart' as a9;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/concluir_treino',
        uri: Uri.parse('/concluir_treino'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.ConcluirTreinoPage(),
        ),
      ),
      RouteEntity(
        key: '/criar_conta',
        uri: Uri.parse('/criar_conta'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.CriarConta(),
        ),
      ),
      RouteEntity(
        key: '/criar_treino',
        uri: Uri.parse('/criar_treino'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.CriarTreinoPage(),
        ),
      ),
      RouteEntity(
        key: '/exercicios',
        uri: Uri.parse('/exercicios'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.ExerciciosPage(),
        ),
      ),
      RouteEntity(
        key: '/historico',
        uri: Uri.parse('/historico'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.HisoticoPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a5.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a6.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a7.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/treino',
        uri: Uri.parse('/treino'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a8.TreinoPage(),
        ),
      ),
      RouteEntity(
        key: '/usuario',
        uri: Uri.parse('/usuario'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a9.UsuarioPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  concluirTreino: '/concluir_treino',
  criarConta: '/criar_conta',
  criarTreino: '/criar_treino',
  exercicios: '/exercicios',
  historico: '/historico',
  home: '/home',
  login: '/login',
  splash: '/splash',
  treino: '/treino',
  usuario: '/usuario',
);
