// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/(public)/criar_treino_page.dart' as a0;
import 'app/(public)/home_page.dart' as a1;
import 'app/(public)/splash_page.dart' as a2;
import 'app/(public)/treino_page.dart' as a3;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/criar_treino',
        uri: Uri.parse('/criar_treino'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.CriarTreinoPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/treino',
        uri: Uri.parse('/treino'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.TreinoPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  criarTreino: '/criar_treino',
  home: '/home',
  splash: '/splash',
  treino: '/treino',
);
